### ISSUE TITLE
Install fails on Apple M1

### ISSUE THREAD

**Issue by mjknoxie** [strongdm/comply#102]
brew install fails on Apple silicon. 

```
brew install comply
==> Installing comply from strongdm/comply
==> Downloading https://github.com/strongdm/comply/archive/v1.5.1.tar.gz
Already downloaded: /Users/mjknoxie/Library/Caches/Homebrew/downloads/aa4bb8ed781fe561a2ce511a8705eafc91bd8112763b75bd2f432be12e694430--comply-1.5.1.tar.gz
==> make brew
Last 15 lines from /Users/mjknoxie/Library/Logs/Homebrew/comply/01.make:
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/hashicorp/go-retryablehttp v0.6.7
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading golang.org/x/sys v0.0.0-20200909081042-eff7692f9009
go: downloading github.com/russross/blackfriday v1.5.3-0.20200218234912-41c5fccfd6f6
go: downloading github.com/lunixbochs/vtclean v1.0.0
go: downloading github.com/opencontainers/go-digest v1.0.0
../../../../pkg/mod/github.com/cpuguy83/go-md2man/v2@v2.0.0/md2man/md2man.go:4:2: missing go.sum entry for module providing package github.com/russross/blackfriday/v2 (imported by github.com/cpuguy83/go-md2man/v2/md2man); to add:
	go get github.com/cpuguy83/go-md2man/v2/md2man@v2.0.0
make: *** [brew] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by ulte** [comment]
if it's any consolation I get the same error on a non M1 macbook pro Big Sur

**Comment by mjknoxie** [comment]
argh, it's not building on my Intel mac mini either, macOS 10.15. This looks like the go-md2man project. 


`==> make brew
Last 15 lines from /Users/michael.knox/Library/Logs/Homebrew/comply/01.make:
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/trivago/tgo v1.0.7
go: downloading golang.org/x/sys v0.0.0-20200909081042-eff7692f9009
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading github.com/russross/blackfriday v1.5.3-0.20200218234912-41c5fccfd6f6
go: downloading github.com/lunixbochs/vtclean v1.0.0
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/opencontainers/go-digest v1.0.0
../../../../pkg/mod/github.com/cpuguy83/go-md2man/v2@v2.0.0/md2man/md2man.go:4:2: missing go.sum entry for module providing package github.com/russross/blackfriday/v2 (imported by github.com/cpuguy83/go-md2man/v2/md2man); to add:
	go get github.com/cpuguy83/go-md2man/v2/md2man@v2.0.0
make: *** [brew] Error 1`

**Comment by franklouwers** [comment]
Can confirm this is not M1 specific

**Comment by AstroBoy269** [comment]
I can confirm that I’m getting the same issue with on Intel MacMini with BigSur, 11.2.3 and it's failing at the same point as well.
```
==> make brew
Last 15 lines from /Users/lcr/Library/Logs/Homebrew/comply/01.make:
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/hashicorp/go-retryablehttp v0.6.7
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading github.com/jcelliott/lumber v0.0.0-20160324203708-dd349441af25
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading github.com/lunixbochs/vtclean v1.0.0
go: downloading github.com/russross/blackfriday v1.5.3-0.20200218234912-41c5fccfd6f6
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/opencontainers/go-digest v1.0.0
../../../../pkg/mod/github.com/cpuguy83/go-md2man/v2@v2.0.0/md2man/md2man.go:4:2: missing go.sum entry for module providing package github.com/russross/blackfriday/v2 (imported by github.com/cpuguy83/go-md2man/v2/md2man); to add:
	go get github.com/cpuguy83/go-md2man/v2/md2man@v2.0.0
make: *** [brew] Error 1
```

**Comment by franklouwers** [comment]
Is there a fix available?

**Comment by isaacpz** [comment]
Although the homebrew installation is broken, `go get github.com/strongdm/comply` works fine.

**Comment by mthibode13** [comment]
Worked for me today, but now I can't get comply build past the request for pandoc. Pandoc is installed, and it recognizes that it is installed; however, it still gives the error: 

me@M1PB Comply % comply build

[✔] pandoc binary installed and in PATH
[✔] pandoc version compatible
[✖] pdflatex binary installed and in PATH
[✔] docker binary installed
[✖] docker running

NAME:
   comply build - generate a static website summarizing the compliance program

USAGE:
   comply build [arguments...]
2021/07/19 16:53:15 

Please install either Docker or the pandoc package and re-run `build`.

**Comment by camposer** [comment]
I just successfully run pandoc in my M1 today. Here the steps:

* Install pandoc
```
brew install pandoc basictex
```

* Clone comply and build
```
git clone https://github.com/strongdm/comply.git
cd comply
echo "COMPLY_USE_LOCAL_PANDOC=true" > .env
mkdir my-company && cd my-company
go run ../comply.go init
go run ../comply.go build
```

The key here is to force local pandoc (not docker).

**Comment by wallrony** [comment]
Hey folks! New instructions were added to the [README.md](https://github.com/strongdm/comply/blob/master/README.md) talking about Comply installation via HomeBrew. Please take a look.
