### ISSUE TITLE
Docker - Deploy Latest

### ISSUE THREAD

**Issue by brdlyptrs** [strongdm/comply#117]
### What
Bump the current comply version in the Dockerfile to use latest release: `1.5.2`, and deploy to docker hub.

### Why
Always nice to have the latest updates, and running docker containers is a good way to both run and isolate tools in a controlled environment.

**Comment by camposer** [comment]
Thanks for the feedback @brdlyptrs 
The version that you see in the Dockerfile is just a base version in case there's no explicit COMPLY_VERSION. If you want to build the project I recommend you to take a look at the [Makefile](https://github.com/strongdm/comply/blob/master/Makefile). Specially [interesting for you](https://github.com/strongdm/comply/blob/master/Makefile#L117):

```
docker build --build-arg COMPLY_VERSION=`cat VERSION` -t strongdm/comply .
```
