### ISSUE TITLE
comply build hangs forever

### ISSUE THREAD

**Issue by zfLQ2qx2** [strongdm/comply#120]
It appears that "comply build" hangs forever after generating a couple lines of output:

```
[Container] 2021/11/16 15:46:12 Running command ./comply build
--
68 | Pulling docker image
69 | Pulling strongdm/pandoc:edge Docker image (this will take some time) ...........templates/index.ace -> output/index.html
70 | . done.
71 | policies/access.md -> output/Policies-AOTP.pdf
72 | policies/application.md -> output/Policies-ASP.pdf

```

How can I diagnose what is happening here?

**Comment by camposer** [comment]
Could you please add the full output? OS version? How you're using comply?

**Comment by dlorenc** [comment]
I hit this too. Any chance you're on an M1 macbook? It looks like the image `strongdm/pandoc:edge` isn't built for arm CPUs which causes some issues.

**Comment by camposer** [comment]
If that's the case, you could do the following:

1. Clone the repo

2. Build a pandoc image using [this Dockerfile](https://github.com/strongdm/comply/blob/master/build/Dockerfile)
```
cd build
docker rmi strongdm/pandoc:edge
docker build -t strongdm/pandoc:edge .
```

2. Specify a custom pandoc image via env variables:
```
cd .. # comply root dir
echo "COMPLY_USE_LOCAL_PANDOC=true" > .env
```

3. Use comply:
```
mkdir my-company
cd my-company
go run ../comply.go init
go build ../comply.go build
```
