### ISSUE TITLE
Build get stuck and no pdf's are generated

### ISSUE THREAD

**Issue by fbonawiede** [strongdm/comply#124]
When I run `comply build` the index file is generated and the first pdf.md

<img width="385" alt="Screenshot 2022-04-28 at 10 50 27" src="https://user-images.githubusercontent.com/691791/165716992-bdee0112-ea8d-48c1-8111-8b6713ed8af7.png">

<img width="409" alt="image" src="https://user-images.githubusercontent.com/691791/165717402-5d31576e-3747-4151-af97-e0188b60844c.png">

comply VERSION:1.6.0

pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4

**Comment by camposer** [comment]
Hi @fbonawiede 

How are you using comply? Via brew, docker? I presume you're using Mac, is it Intel or M1?

**Comment by fbonawiede** [comment]
brew, Mac with M1

**Comment by camposer** [comment]
Thanks @fbonawiede 

Unfortunately, the binary available in brew isn't -yet- compatible with M1. You'd need to clone the repo, build and use the binary, or use docker.

Maybe it's easier to start with docker. [Here's the image](https://hub.docker.com/r/strongdm/comply)

**Comment by fbonawiede** [comment]
@camposer Thanks! But I actually got it working now (not via docker) and I didn't compile it.
