### ISSUE TITLE
Docker Requirement?

### ISSUE THREAD

**Issue by trevrr** [strongdm/comply#35]
I'm wondering why the requirement for Docker in the comply build? I think pandoc is the only requirement being met by Docker? For OS X people you're already doing a homebrew install. Would it be easier to install pandoc instead of requiring gigs and gigs of a docker install to be there already?

**Comment by magnua** [comment]
For anyone else wondering about this, here's what @jmccarthy had to say about this in Slack:

_We couldn't find a consistent, cross-platform `pandoc` installation, so Docker was the best guaranteed option.
All `comply` cares about is that there is a working `pandoc` available so I could see transitioning to a configurable option if you've already got it installed via other means._

**Comment by jmccarthy** [comment]
Resolved by 49e950c3c029fed8c05c29cfd6dd190122505be7

**Comment by jmccarthy** [comment]
Included in release v1.2.0

**Comment by trevrr** [comment]
Super work on this folks. Very impressed by this and everything that I've seen so far.
