### ISSUE TITLE
Fresh install doesn't build

### ISSUE THREAD

**Issue by robguilfoyle** [strongdm/comply#44]
After init'ing from homebrew and running `comply init` and following prompts, running `comply build` yields this: 

```
Please install either Docker or the pandoc package and re-run `build`
```

Both docker and pandoc are installed. Could this be a gopath issue?

**Comment by jmccarthy** [comment]
@robguilfoyle could you confirm `comply -v` is 1.2.3? 

If not, could you try:

brew upgrade comply

Which macOS release are you on? High Sierra?

**Comment by robguilfoyle** [comment]
false alarm, I had a conflict with Docker for Mac and Docker. Apologies
