### ISSUE TITLE
Gitlab Integration

### ISSUE THREAD

**Issue by masonhensley** [strongdm/comply#50]
Hey Justin, 

Cool project, I'm kicking the tires on using this for an upcoming compliance project. 

If I or someone on my team wanted to contribute a gitlab integration, would that be ok? Do you have any contribution guidelines?

We're not a golang shop, but your github/jira implementations (in `/internal`) seem straight forward enough to replicate.

I would assume that we'd have to use:

https://github.com/xanzy/go-gitlab

**Comment by jmccarthy** [comment]
@masonhensley we'd love to add gitlab! Even if you can just get a PR with a draft implementation, I'd be happy to help test it & maintain it. 

Feel free to swing by the Slack channel (linked in README.md) if you want to discuss comply usage in general.

**Comment by masonhensley** [comment]
MR here - https://github.com/strongdm/comply/pull/51

**Comment by masonhensley** [comment]
Closing. Fixed by https://github.com/strongdm/comply/pull/51
