### ISSUE TITLE
GitLab ticket tracking

### ISSUE THREAD

**Issue by godfather1824** [strongdm/comply#75]
When using GitLab, all ticket status show as 0 even though there are active tickets. Is there something specific that would have to be changed to get this to show valid counts? The creation of tickets works just fine.
![image](https://user-images.githubusercontent.com/7373891/67979499-c8bd0900-fbf2-11e9-978f-af8bdb773da5.png)

**Comment by gruen** [comment]
Made a PR for this. https://github.com/strongdm/comply/pull/84

**Comment by camposer** [comment]
PR already merged
