### ISSUE TITLE
JIRA api not working

### ISSUE THREAD

**Issue by mikosan42** [strongdm/comply#89]
comply sync gives the following error:

2020/06/10 10:12:22 unable to fetch Jira issues: No response returned: Get "/rest/api/2/search?jql=labels%3Dcomply&startAt=0&maxResults=1000&expand=&fields=&validateQuery=": unsupported protocol scheme ""

**Comment by mikosan42** [comment]
The url in the comply.yaml is: 3rd-eyes.atlassian.net, which is the url of our JIRA instance.

**Comment by adamdecaf** [comment]
`unsupported protocol scheme` tells me that value should be `https://3rd-eyes.atlassian.net`.

**Comment by nemozny** [comment]
Jira API is working, tested just now.
